name: nwb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py312h05f76fc_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asciitree=0.3.3=py_2
  - astroid=3.3.11=py312h2e8e312_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - asyncssh=2.21.0=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - bcrypt=4.3.0=py312hdabe01f_2
  - beautifulsoup4=4.13.5=pyha770c72_0
  - bidsschematools=0.7.2=pyhd8ed1ab_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=25.1.0=pyh866005b_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py312hbb81ca0_4
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py312he06e257_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - ci-info=0.3.0=pyhd8ed1ab_1
  - click=8.2.1=pyh7428d3b_0
  - click-didyoumean=0.3.1=pyhd8ed1ab_1
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hf90b1b7_2
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.12.11=py312hd8ed1ab_0
  - cryptography=45.0.7=py312h84d000f_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - dandi=0.67.2=py312h2e8e312_0
  - dandischema=0.11.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.16=py312ha1a9051_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.0=pyhd8ed1ab_0
  - dnspython=2.8.0=pyhcf101f3_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - etelemetry=0.3.1=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fasteners=0.19=pyhd8ed1ab_1
  - ffmpeg=8.0.0=gpl_he3062b8_906
  - flake8=7.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.0=py312h05f76fc_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - fscacher=0.4.4=pyhd8ed1ab_1
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - fzf=0.65.2=hb13f615_0
  - gdk-pixbuf=2.44.3=h1f5b9c4_0
  - glib=2.86.0=ha3795fc_0
  - glib-tools=2.86.0=he647baa_0
  - glslang=16.0.0=h5b34520_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=nompi_py312h03cd2ba_101
  - harfbuzz=12.0.0=h5f2951f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - hdmf=4.1.0=pyhd8ed1ab_0
  - hdmf_zarr=0.11.3=pyha770c72_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - humanize=4.13.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - imath=3.2.1=h1608b31_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - interleave=0.3.0=pyhd8ed1ab_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - isodate=0.7.2=pyhd8ed1ab_1
  - isort=6.0.1=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.1.3=py312h2615798_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyring=25.6.0=pyh7428d3b_0
  - keyrings.alt=5.0.2=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py312h78d62e6_1
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.1=default_ha2db4b5_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.1.0=h1383e82_5
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.86.0=h5f26cbf_0
  - libgomp=15.1.0=h1383e82_5
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libjxl=0.11.1=hb7713f0_4
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblapacke=3.9.0=35_h3ae206f_mkl
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.12.0=qt6_py312h28e8626_605
  - libopenvino=2025.2.0=hbf28c98_1
  - libopenvino-auto-batch-plugin=2025.2.0=hdd9a157_1
  - libopenvino-auto-plugin=2025.2.0=hdd9a157_1
  - libopenvino-hetero-plugin=2025.2.0=hc39e7c6_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-ir-frontend=2025.2.0=hc39e7c6_1
  - libopenvino-onnx-frontend=2025.2.0=hee3bb10_1
  - libopenvino-paddle-frontend=2025.2.0=hee3bb10_1
  - libopenvino-pytorch-frontend=2025.2.0=hac47afa_1
  - libopenvino-tensorflow-frontend=2025.2.0=h293fe96_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hac47afa_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_1
  - librsvg=2.58.4=ha14e162_4
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.1.0=h518811d_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h550210a_0
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.313.0=h477610d_1
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.0=ha29bfb0_0
  - libxml2-16=2.15.0=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - littleutils=0.2.4=pyhd8ed1ab_1
  - llvm-openmp=20.1.8=hfa2b4ca_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h31fea79_1
  - mat73=0.65=pyhd8ed1ab_1
  - matplotlib=3.9.1=py312h2e8e312_1
  - matplotlib-base=3.9.1=py312h90004f6_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2024.2.2=h57928b3_16
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py312hf90b1b7_1
  - multidict=6.6.3=py312h05f76fc_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numcodecs=0.15.1=py312h72972c8_0
  - numpy=2.3.3=py312ha72d056_0
  - numpydoc=1.9.0=pyhe01879c_1
  - nwbinspector=0.6.5=pyhd8ed1ab_1
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.12.0=qt6_py312h64de955_605
  - openexr=3.4.0=h667fd73_1
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.3=h24db6dd_1
  - openjph=0.24.1=hf13a347_0
  - openpyxl=3.1.5=py312h83acffa_2
  - openssl=3.6.0=h725018a_0
  - outdated=0.2.2=pyhd8ed1ab_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py312hc128f0a_0
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - pandoc=3.8=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h3402e2f_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h5ee8bfe_3
  - pingouin=0.5.5=pyhd8ed1ab_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h31fea79_0
  - psutil=7.0.0=py312he06e257_1
  - pthread-stubs=0.4=h0e40799_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h372dad0_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py312h4c995e2_605
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pycryptodomex=3.23.0=py312he06e257_1
  - pydantic=2.11.9=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312h8422cdd_0
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=3.3.8=pyhe01879c_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.6.0=py312he06e257_0
  - pynwb=3.1.2=pyhd8ed1ab_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyout=0.8.1=py312h2e8e312_2
  - pyparsing=3.2.4=pyhcf101f3_0
  - pyqt=5.15.11=py312he11f4ca_1
  - pyqt5-sip=12.17.0=py312h275cf98_1
  - pyqtwebengine=5.15.11=py312h5f40ce4_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.9=h3f84c4b_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-gssapi=1.10.0=py312hd572b79_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.12.2=pyhff2d567_0
  - python-lsp-server-base=1.12.2=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pywin32=311=py312h829343e_1
  - pywin32-ctypes=0.2.3=py312h2e8e312_2
  - pyyaml=6.0.2=py312h31fea79_2
  - pyzmq=27.1.0=py312hbb5da91_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=hc790b64_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=hb098fff_5
  - qt-webengine=5.15.15=h087ee03_1
  - qt6-main=6.9.2=ha0de62e_3
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.6.1=pyhd8ed1ab_2
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.3=pyhd8ed1ab_1
  - rav1e=0.7.1=ha073cba_3
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3987=1.3.8=pyhd8ed1ab_1
  - rich=14.1.0=pyhe01879c_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.27.1=py312hdabe01f_1
  - rtree=1.4.1=pyh11ca60a_0
  - ruamel.yaml=0.18.15=py312he06e257_1
  - ruamel.yaml.clib=0.2.12=py312he06e257_1
  - scikit-learn=1.7.2=py312h91ac024_0
  - scipy=1.16.2=py312h33376e8_0
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.22=h5112557_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=haa9a63f_0
  - sip=6.10.0=py312h275cf98_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=8.3.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spirv-tools=2025.1=hc790b64_0
  - spyder=6.0.8=hd8ed1ab_0
  - spyder-base=6.0.8=py312h2e8e312_0
  - spyder-kernels=3.0.5=win_pyh7428d3b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312h196c9fc_0
  - superqt=0.7.6=pyhb6d5dde_0
  - svt-av1=3.1.2=hac47afa_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.13.0=h18a62a1_3
  - tenacity=9.1.2=pyhd8ed1ab_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py312he06e257_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.11.0=py312ha1a9051_1
  - unicodedata2=16.0.0=py312he06e257_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - watchdog=6.0.0=py312h2e8e312_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py312he06e257_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xarray=2025.9.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=h6a83c73_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.20.1=py312h31fea79_0
  - zarr=2.18.7=pyhd8ed1ab_0
  - zarr-checksum=0.4.2=pyhd8ed1ab_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py312he5662c2_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - ndx-events==0.4.0
      - ndx-photometry==0.4.0
prefix: C:\Users\deburke\AppData\Local\miniconda3\envs\nwb
